### ISSUE TITLE
Sorting lyfecycle methogs from the start

### ISSUE THREAD

**Issue by grub-** [armandAkop/Lifecycle-Sorter#2]
It might be much more convenient if here will be option to sort methods from start among other methods not from the end as it is now.

**Comment by armandAkop** [comment]
Thanks for the feedback, I'm putting this down as a feature to add!

**Comment by armandAkop** [comment]
Hey grub-, I made the changes and will upload them to the plugin repository today. It'll be up early this week I assume. I'll update you when it's available.
