### ISSUE TITLE
class with name "Action.SortStartAction" not found [Plugin: com.armandakopian.lifecyclesorter]

### ISSUE THREAD

**Issue by pulque** [armandAkop/Lifecycle-Sorter#6]
10:05:22 AM Plugin Error: Lifecycle Sorter threw an uncaught PluginException. Disable Plugin
10:05:22 AM PluginException: class with name "Action.SortStartAction" not found [Plugin: com.armandakopian.lifecyclesorter]
10:05:24 AM EmptyThrowable: Null child action in group Sort Lifecycle Methods (Sorts the lifecycle methods of an activity) of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=sortStart

Android studio 2.1.2
I download zip from github, then install plugin with disk.
Am I install with a wrong way?

**Comment by i-aakopian** [comment]
@pulque Did you figure this out?

**Comment by i-aakopian** [comment]
This used to happen on OSX when I had compiled the plugin with a newer version of Java (1.7) so I recompiled with 1.6 and it seemed to fix it.

**Comment by pulque** [comment]
Yes, need download jar.
https://plugins.jetbrains.com/plugin/7742?pr=idea
